### ISSUE TITLE
since county is focus, make county default map and switch to left and put state on right?

### ISSUE THREAD

**Issue by jkoschinsky** [GeoDaCenter/covid#18] opened 2020-03-26 20:11 UTC

**Comment by Makosak** [comment] 2020-03-26 21:37
I kind of like the state map better instead to start with -- it serves as a validation for what others are seeing, and better for landing page?

**Comment by jkoschinsky** [comment] 2020-03-26 21:38
ok, your call

Julia Koschinsky, Ph.D.
Executive Director
Center for Spatial Data Science
University of Chicago
https://spatial.uchicago.edu/

<https://spatial-data-science-conference.com/>
________________________________

**Comment by Makosak** [comment] 2020-03-26 21:52
@lixun910 what about this as landing -- switching back to states (as this will match what folks are viewing at JHU, 1P3A, others) but make the center of the map slightly off-center so it's positioned like so? The center of the map will not be the center of the US, but more around Tennessee, so it's to the left of the toolbar.

![Screen Shot 2020-03-26 at 4 48 56 PM](https://user-images.githubusercontent.com/4277692/77700374-152e2a00-6f82-11ea-8b45-c42ce7506dfe.png)

**Comment by lixun910** [comment] 2020-03-26 22:02
Sure.

FYI, the zoom doesn’t work for now – the deck.gl document is not clear

**Comment by Makosak** [comment] 2020-03-29 23:43
After thinking about this some more and going over the feedback. What if we indeed switch to county as landing page --> but do the population adjusted rate? That adds a lot more meat to the visualization and we don't start with an empty-looking map that the high-pop cities bias. What do you think about landing on this image? It can highlight how far the virus has spread, as the clustering maps may not catch the full spread. @jkoschinsky @lixun910 ?
![Screen Shot 2020-03-29 at 6 43 01 PM](https://user-images.githubusercontent.com/4277692/77864270-347cbf80-71ed-11ea-921f-ebfdf20ae889.png)

**Comment by jkoschinsky** [comment] 2020-03-29 23:55
agree on counties as default
can we alternative between this map and the cluster one to highlight the spatial analytics, which differentiates us from the increasing number of other county maps?

Julia Koschinsky, Ph.D.
Executive Director
Center for Spatial Data Science
University of Chicago
https://spatial.uchicago.edu/

<https://spatial-data-science-conference.com/>
________________________________

**Comment by lixun910** [comment] 2020-03-30 00:43
Sure: )


Xun Li, Ph.D.

Assistant Director of Data Science
Center for Spatial Data Science
University of Chicago

**Comment by Makosak** [comment] 2020-03-30 01:36
I would vote for choropleth map, not the cluster map. The cluster map misses how widespread the virus is, and the choropleth I think would be a better intro as the user will be more informed going from widespread cases via natural breaks to the cluster map which has more statistical error and blank spaces. An area of non-significance doesn't mean there is no COVID, so we need to be careful here.

**Comment by Makosak** [comment] 2020-03-30 01:37
There are so many challenges with LISA interpretation -- seeing this as we start to field questions about why towns were flagged as cluster, and will see this more as one day a county will be in a cluster and the next day it won't (because of shift in cases nationally). Informatics rules say start with the simplest access to information, then get more complex from there.

**Comment by lixun910** [comment] 2020-03-30 02:10
County (confirmed count per 10K Population) choropleth  is default now.


Xun Li, Ph.D.

Assistant Director of Data Science
Center for Spatial Data Science
University of Chicago

**Comment by Makosak** [comment] 2020-04-02 18:33
Ok, closing as a compromise for now, we can revisit again if needed!

**Closed by Makosak** 2020-04-02 18:33 UTC
Labels: enhancement
