### ISSUE TITLE
Negative counts in tooltip

### ISSUE THREAD

**Issue by rbrtmrtn** [GeoDaCenter/covid#46] opened 2020-04-27 23:10 UTC
For Weld County, CO (just north of Denver) on 4/26 there was a negative new deaths count:

![Screen Shot 2020-04-27 at 6 06 48 PM](https://user-images.githubusercontent.com/1463553/80429571-12409500-88b2-11ea-81d3-58f1afd06eac.png)

Fairly certain this is just a glitch in the data but we might want to consider defaulting these values to something like "Error", just to prevent any confusion.

**Comment by lixun910** [comment] 2020-04-28 00:17
Agree. A negative number in this case is ... Unless the data in previous day was incorrectly reported, and the county correct it in the next day.  Qinyun, can you help to check the USAFacts csv file? Thanks!

**Comment by linqinyu** [comment] 2020-04-28 13:35
@lixun910 That is exactly the case you described! The case number is 82 for 4/24, 78 for 4/25, and 79 for 4/26. 

Also note from USAFacts: (not sure whether this particular county is included or not):
Note from April 18: Certain states have changed their methodology in reporting deaths due to COVID-19. As a result, we are holding off on reporting death data in a few key states (New York is notable among these states due to the high number of confirmed cases and deaths). USAFacts is committed to providing official numbers confirmed by state or local health agencies, and we will appropriately backfill the death data when we receive more guidance from the CDC and relevant health departments.

**Comment by linqinyu** [comment] 2020-04-28 13:36
@rbrtmrtn this is something that can be checked automatically.

**Closed** 2020-05-11 17:44 UTC
Labels: UI, bug
